"use client";

import { useEffect, useState } from "react";
import {DatabaseAdmin, RealLogin, RealSignup} from "@/components/database-ui";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Download, Eye, FileSpreadsheet, Image as ImageIcon, ListFilter, LockKeyhole, Mail, MapPin, Menu, MoreHorizontal, Plus, Search, Settings, Snowflake, TicketCheck, UserCheck, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

type View = "events" | "detail" | "signup" | "success" | "login" | "admin";

type EventStatus = "Anmeldung offen" | "Anmeldung startet bald" | "Warteliste" | "Ausgebucht" | "Anmeldung geschlossen";
type EventItem = { id:number; title:string;detailHeading?:string; date:string; dateLong:string; place:string; status:EventStatus; spots?:number;onlyWaitlist?:boolean;waitlist?:boolean;starts?:string;ends?:string;imageUrl?:string;showSpots?:boolean; imagePosition:string; description:string; info:string[]; registrationInfo:string; skillLevels:string[] };


function statusClass(status:string){if(status==="Anmeldung offen"||status==="BESTÄTIGT")return"status open";if(status==="Warteliste"||status==="WARTELISTE")return"status wait";if(status==="Anmeldung startet bald")return"status soon";return"status closed"}
function Brand({compact=false}:{compact?:boolean}){return <div className={compact?"brand compact":"brand"}><img className="brand-logo" src="/schiteam-logo.png" alt="Schiteam Union Julbach"/></div>}

export default function Home(){
 const [events,setEvents]=useState<EventItem[]>([]),[loadError,setLoadError]=useState(""),[loading,setLoading]=useState(true);
 async function loadEvents(){try{const response=await fetch("/api/platform",{cache:"no-store"});const data=await response.json() as {events:EventItem[];error?:string};if(!response.ok)throw new Error(data.error);setEvents(data.events);setLoadError("");}catch(e){setLoadError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void loadEvents();const timer=setInterval(()=>void loadEvents(),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const next=events.flatMap(event=>[event.starts,event.ends]).filter(Boolean).map(value=>Date.parse(value!)-Date.now()).filter(delay=>delay>0);if(!next.length)return;const timer=setTimeout(()=>void loadEvents(),Math.min(...next,2147483000)+50);return()=>clearTimeout(timer)},[events]);
 const[view,setView]=useState<View>("events"),[selected,setSelected]=useState<EventItem|null>(null),[mobileNav,setMobileNav]=useState(false);
 useEffect(()=>{if(view==="detail"||view==="signup")setSelected(current=>events.find(event=>event.id===current?.id)||current)},[events,view]);
 useEffect(()=>{const context=typeof document!=="undefined"?(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext:undefined;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"start_event_registration",title:"Veranstaltungsanmeldung starten",description:"Öffnet das Anmeldeformular für eine Veranstaltung des Schiteam Julbach.",inputSchema:{type:"object",properties:{eventId:{type:"number"}},required:["eventId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const id=Number((input as {eventId?:number})?.eventId),event=events.find(x=>x.id===id);if(!event||!["Anmeldung offen","Warteliste"].includes(event.status))throw new Error("Anmeldung nicht verfügbar");setSelected(event);setView("signup");return{eventId:id,title:event.title,state:"registration_opened"}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[events]);
 const go=(next:View)=>{setView(next);setMobileNav(false);window.scrollTo({top:0,behavior:"smooth"})};const showEvent=(event:EventItem)=>{setSelected(event);go("detail")};
 if(view==="admin")return <DatabaseAdmin exit={()=>{void loadEvents();go("events")}}/>;
 if(view==="login")return <RealLogin onLogin={()=>go("admin")} onBack={()=>go("events")}/>;
 return <div className="site-shell"><header className="public-header"><button className="brand-button" onClick={()=>go("events")}><Brand/></button><nav className={mobileNav?"public-nav open":"public-nav"}><button className="active" onClick={()=>go("events")}>Veranstaltungen</button><a href="#verein">Über uns</a><a href="#kontakt">Kontakt</a></nav><div className="header-season"><span>Saison</span><button>2026/27 <ChevronDown size={16}/></button></div><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X/>:<Menu/>}</button></header>
 {view==="events"&&<>{loadError?<div className="form-page" role="alert">{loadError}<Button onClick={loadEvents}>Erneut versuchen</Button></div>:events.length?<EventsOverview events={events} onSelect={showEvent}/>:<main className="form-page">{loading?"Veranstaltungen werden geladen …":"Derzeit sind keine Veranstaltungen veröffentlicht."}</main>}</>} {view==="detail"&&selected&&<EventDetail event={selected} back={()=>go("events")} signup={()=>go("signup")}/>} {view==="signup"&&selected&&<RealSignup event={selected} back={()=>go("detail")} submit={status=>{setSelected({...selected,status:status==="waitlist"?"Warteliste":"Anmeldung offen"});void loadEvents();go("success")}}/>} {view==="success"&&selected&&<Success event={selected} done={()=>go("events")}/>} 
 <footer id="kontakt" className="public-footer"><div><Brand compact/><p>Snow. Fun. Friends.<br/>Nachwuchs. Action. Teamspirit.</p></div><div><strong>Schiteam Julbach</strong><a href="mailto:info@schiteam-julbach.at">info@schiteam-julbach.at</a><span>4162 Julbach · Oberösterreich</span></div><div><strong>Information</strong><a href="#">Datenschutz</a><a href="#">Impressum</a><button onClick={()=>go("login")}><LockKeyhole size={14}/> Admin Login</button></div><small>© 2026 Schiteam Julbach</small></footer></div>;
}

function EventsOverview({onSelect,events}:{onSelect:(e:EventItem)=>void;events:EventItem[]}){return <main><section className="intro"><div><span className="eyebrow"><Snowflake size={16}/> SAISON 2026/27</span><h1>Gemeinsam<br/><em>auf die Piste.</em></h1><p>Skikurse, Trainings und gemeinsame Ausfahrten – entdecke unsere Veranstaltungen und sichere dir deinen Platz.</p></div><div className="intro-stat"><span>{events.length}</span><p>Veranstaltungen<br/>in dieser Saison</p></div></section><section className="events-section"><div className="section-heading"><div><span className="eyebrow">VERANSTALTUNGEN</span><h2>Das steht als Nächstes an</h2></div><p>Alle Termine der Saison 2026/27 auf einen Blick.</p></div><div className="event-grid">{events.map(event=><article className="event-card" key={event.id}><button className="event-image" onClick={()=>onSelect(event)}><img src={event.imageUrl||"/schiteam-momente.jpeg"} alt="Schiteam Julbach im Schnee" style={{objectPosition:event.imagePosition}}/><span className="date-tile">{event.date.split(" ")[0]}<small>{event.date.split(" ").slice(1).join(" ")}</small></span></button><div className="event-card-body"><div className="card-topline"><span className={statusClass(event.status)}>{event.status}</span>{event.showSpots!==false&&event.spots!==undefined&&<span className="spots"><Users size={15}/>{event.spots} Plätze frei</span>}</div><h3>{event.title}</h3><p><MapPin size={16}/>{event.place}</p><button className="text-link" onClick={()=>onSelect(event)}>Details ansehen <ArrowRight size={17}/></button></div></article>)}</div></section><section id="verein" className="club-strip"><div><span className="eyebrow light">SCHITEAM JULBACH</span><h2>Ehrenamtlich.<br/>Sportlich. Miteinander.</h2></div><p>Wir bringen Kinder, Jugendliche und Erwachsene mit Begeisterung in den Schnee – und schaffen Erlebnisse, die verbinden.</p></section></main>}

function EventDetail({event,back,signup}:{event:EventItem;back:()=>void;signup:()=>void}){const disabled=["Ausgebucht","Anmeldung geschlossen","Anmeldung startet bald"].includes(event.status);return <main className="detail-page"><button className="back-link" onClick={back}><ArrowLeft size={18}/> Alle Veranstaltungen</button><section className="detail-hero"><img src={event.imageUrl||"/schiteam-momente.jpeg"} alt="Schiteam Julbach beim Skifahren" style={{objectPosition:event.imagePosition}}/><div className="detail-overlay"><span className={statusClass(event.status)}>{event.status}</span><h1>{event.title}</h1><div className="detail-meta"><span><CalendarDays/>{event.dateLong}</span><span><MapPin/>{event.place}</span></div></div></section><section className="detail-layout"><article><span className="eyebrow">DARUM GEHT’S</span><h2>{event.detailHeading||"Gemeinsam besser Ski fahren."}</h2><p style={{whiteSpace:"pre-line"}}>{event.description}</p><h3>Wichtige Informationen</h3><ul className="info-list">{event.info.map(i=><li key={i}><Check size={18}/>{i}</li>)}</ul></article><aside className="signup-box"><span className="eyebrow">ANMELDUNG</span><h3>{event.status==="Warteliste"?"Platz auf der Warteliste sichern":"Jetzt Platz sichern"}</h3><p>{event.status==="Warteliste"?(event.onlyWaitlist&&!event.waitlist?"Die regulären Plätze sind belegt. Externe Teilnehmende können sich auf die Warteliste setzen lassen.":"Neue Anmeldungen werden auf die Warteliste gesetzt."):event.showSpots===false?"Hier kannst du dich für die Veranstaltung anmelden.":event.spots?`Aktuell sind noch ${event.spots} Plätze verfügbar.`:"Die Anmeldung ist derzeit nicht möglich."}</p><Button disabled={disabled} onClick={signup}>{event.status==="Warteliste"?"Für Warteliste anmelden":"Jetzt anmelden"}<ArrowRight/></Button><small>{event.onlyWaitlist?"Teilnehmende außerhalb von 4162 Julbach kommen zunächst auf die Warteliste.":"Die Anmeldung dauert ca. 2 Minuten."}</small></aside></section></main>}

function Success({event,done}:{event:EventItem;done:()=>void}){const waiting=event.status==="Warteliste";return <main className="success-page"><div className={waiting?"success-icon waiting":"success-icon"}>{waiting?<Clock3/>:<Check/>}</div><span className="eyebrow">{waiting?"WARTELISTE":"ERFOLGREICH ANGEMELDET"}</span><h1>{waiting?"Du stehst auf der Warteliste.":"Schön, dass du dabei bist!"}</h1><p>{waiting?`Wir haben deine Anmeldung für ${event.title} aufgenommen. Dein Platz auf der Warteliste ist gespeichert.`:`Deine Anmeldung für ${event.title} wurde erfolgreich aufgenommen.`}</p><div className="confirmation-card"><div><CalendarDays/><span><small>Termin</small>{event.dateLong}</span></div><div><MapPin/><span><small>Ort</small>{event.place}</span></div><div><Mail/><span><small>Bestätigung</small>Anmeldung dauerhaft gespeichert</span></div></div><Button onClick={done}>Zur Veranstaltungsübersicht</Button></main>}