"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Download, Eye, FileSpreadsheet, ListFilter, LockKeyhole, Mail, MapPin, Menu, MoreHorizontal, MountainSnow, Plus, Search, Settings, Snowflake, TicketCheck, UserCheck, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

type View = "events" | "detail" | "signup" | "success" | "login" | "admin";
type AdminTab = "overview" | "participants" | "settings" | "emails" | "export";
type EventStatus = "Anmeldung offen" | "Anmeldung startet bald" | "Warteliste" | "Ausgebucht" | "Anmeldung geschlossen";
type EventItem = { id:number; title:string; date:string; dateLong:string; place:string; status:EventStatus; spots?:number; imagePosition:string; description:string; info:string[] };

const events: EventItem[] = [
  { id:1,title:"Kinderskikurs – Gruppe 1",date:"27.–29. DEZ",dateLong:"27.–29. Dezember 2026",place:"Hochficht",status:"Anmeldung offen",spots:12,imagePosition:"50% 16%",description:"Drei sportliche Tage im Schnee für junge Skifahrerinnen und Skifahrer. Unsere ausgebildeten Übungsleiter begleiten die Kinder in kleinen, passenden Gruppen.",info:["Treffpunkt täglich um 08:15 Uhr","Kurszeit 09:00–15:00 Uhr","Helmpflicht für alle Teilnehmenden"] },
  { id:2,title:"Kinderskikurs – Gruppe 2",date:"02.–04. JÄN",dateLong:"2.–4. Jänner 2027",place:"Hochficht",status:"Warteliste",imagePosition:"50% 30%",description:"Der zweite Termin unseres beliebten Kinderskikurses – mit viel Bewegung, Spaß und Teamgeist am Hochficht.",info:["Treffpunkt täglich um 08:15 Uhr","Kurszeit 09:00–15:00 Uhr","Helmpflicht für alle Teilnehmenden"] },
  { id:3,title:"Vereinsausflug Schladming",date:"24. JÄN",dateLong:"24. Jänner 2027",place:"Schladming",status:"Anmeldung startet bald",spots:42,imagePosition:"50% 47%",description:"Ein gemeinsamer Skitag für Vereinsmitglieder und Freunde auf der Planai.",info:["Abfahrt 05:30 Uhr in Julbach","Busfahrt inklusive","Tageskarte separat"] },
  { id:4,title:"Flutlichttraining",date:"05. FEB",dateLong:"5. Februar 2027",place:"Hochficht",status:"Anmeldung offen",spots:8,imagePosition:"50% 61%",description:"Techniktraining am Abend für fortgeschrittene Jugendliche und Erwachsene.",info:["Treffpunkt 17:30 Uhr","Training 18:00–20:00 Uhr","Mindestalter 14 Jahre"] },
  { id:5,title:"Vereinsmeisterschaft 2027",date:"21. FEB",dateLong:"21. Februar 2027",place:"Hochficht",status:"Ausgebucht",imagePosition:"50% 76%",description:"Die Vereinsmeisterschaft des Schiteam Julbach mit Wertungen für alle Altersklassen.",info:["Startnummernausgabe ab 08:00 Uhr","Start 10:00 Uhr","Siegerehrung im Anschluss"] },
  { id:6,title:"Saisonabschluss Hinterstoder",date:"20. MÄR",dateLong:"20. März 2027",place:"Hinterstoder",status:"Anmeldung geschlossen",imagePosition:"50% 90%",description:"Zum Saisonende verbringen wir gemeinsam einen entspannten Skitag in Hinterstoder.",info:["Abfahrt 06:00 Uhr","Rückfahrt ca. 17:00 Uhr","Begrenzte Busplätze"] },
];
const participants=[{name:"Anna Hofer",email:"anna.hofer@example.at",year:"2016",time:"18.09. · 19:42",status:"BESTÄTIGT"},{name:"Jonas Reiter",email:"jonas.reiter@example.at",year:"2015",time:"18.09. · 19:51",status:"BESTÄTIGT"},{name:"Lena Gabriel",email:"lena.gabriel@example.at",year:"2017",time:"18.09. · 20:06",status:"BESTÄTIGT"},{name:"Felix Mayr",email:"felix.mayr@example.at",year:"2016",time:"18.09. · 20:14",status:"BESTÄTIGT"}];
const waitlist=[{name:"Paul Leitner",email:"paul.leitner@example.at",year:"2016",time:"19.09. · 08:13",status:"WARTELISTE"},{name:"Mia Berger",email:"mia.berger@example.at",year:"2017",time:"19.09. · 08:26",status:"WARTELISTE"},{name:"Laura Winkler",email:"laura.winkler@example.at",year:"2015",time:"19.09. · 09:02",status:"WARTELISTE"}];

function statusClass(status:string){if(status==="Anmeldung offen"||status==="BESTÄTIGT")return"status open";if(status==="Warteliste"||status==="WARTELISTE")return"status wait";if(status==="Anmeldung startet bald")return"status soon";return"status closed"}
function Brand({compact=false}:{compact?:boolean}){return <div className="brand"><span className="brand-mark"><MountainSnow size={compact?20:24}/></span><span><strong>SCHI TEAM</strong><small>UNION JULBACH</small></span></div>}

export default function Home(){
 const[view,setView]=useState<View>("events"),[selected,setSelected]=useState(events[0]),[adminTab,setAdminTab]=useState<AdminTab>("overview"),[mobileNav,setMobileNav]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{const context=typeof document!=="undefined"?document.modelContext:undefined;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"start_event_registration",title:"Veranstaltungsanmeldung starten",description:"Öffnet das Anmeldeformular für eine Veranstaltung des Schiteam Julbach.",inputSchema:{type:"object",properties:{eventId:{type:"number"}},required:["eventId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const id=Number((input as {eventId?:number})?.eventId),event=events.find(x=>x.id===id);if(!event)throw new Error("Veranstaltung nicht gefunden");setSelected(event);setView("signup");return{eventId:id,title:event.title,state:"registration_opened"}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[]);
 const go=(next:View)=>{setView(next);setMobileNav(false);window.scrollTo({top:0,behavior:"smooth"})};const showEvent=(event:EventItem)=>{setSelected(event);go("detail")};
 if(view==="admin")return <AdminApp selected={selected} setSelected={setSelected} tab={adminTab} setTab={setAdminTab} exit={()=>go("events")} notice={notice} setNotice={setNotice}/>;
 if(view==="login")return <Login onLogin={()=>go("admin")} onBack={()=>go("events")}/>;
 return <div className="site-shell"><header className="public-header"><button className="brand-button" onClick={()=>go("events")}><Brand/></button><nav className={mobileNav?"public-nav open":"public-nav"}><button className="active" onClick={()=>go("events")}>Veranstaltungen</button><a href="#verein">Über uns</a><a href="#kontakt">Kontakt</a></nav><div className="header-season"><span>Saison</span><button>2026/27 <ChevronDown size={16}/></button></div><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X/>:<Menu/>}</button></header>
 {view==="events"&&<EventsOverview onSelect={showEvent}/>} {view==="detail"&&<EventDetail event={selected} back={()=>go("events")} signup={()=>go("signup")}/>} {view==="signup"&&<Signup event={selected} back={()=>go("detail")} submit={()=>go("success")}/>} {view==="success"&&<Success event={selected} done={()=>go("events")}/>} 
 <footer id="kontakt" className="public-footer"><div><Brand compact/><p>Snow. Fun. Friends.<br/>Nachwuchs. Action. Teamspirit.</p></div><div><strong>Schiteam Julbach</strong><a href="mailto:info@schiteam-julbach.at">info@schiteam-julbach.at</a><span>4162 Julbach · Oberösterreich</span></div><div><strong>Information</strong><a href="#">Datenschutz</a><a href="#">Impressum</a><button onClick={()=>go("login")}><LockKeyhole size={14}/> Admin Login</button></div><small>© 2026 Schiteam Julbach</small></footer></div>;
}

function EventsOverview({onSelect}:{onSelect:(e:EventItem)=>void}){return <main><section className="intro"><div><span className="eyebrow"><Snowflake size={16}/> SAISON 2026/27</span><h1>Gemeinsam<br/><em>auf die Piste.</em></h1><p>Skikurse, Trainings und gemeinsame Ausfahrten – entdecke unsere Veranstaltungen und sichere dir deinen Platz.</p></div><div className="intro-stat"><span>6</span><p>Veranstaltungen<br/>in dieser Saison</p></div></section><section className="events-section"><div className="section-heading"><div><span className="eyebrow">VERANSTALTUNGEN</span><h2>Das steht als Nächstes an</h2></div><p>Alle Termine der Saison 2026/27 auf einen Blick.</p></div><div className="event-grid">{events.map(event=><article className="event-card" key={event.id}><button className="event-image" onClick={()=>onSelect(event)}><img src="/schiteam-momente.jpeg" alt="Schiteam Julbach im Schnee" style={{objectPosition:event.imagePosition}}/><span className="date-tile">{event.date.split(" ")[0]}<small>{event.date.split(" ").slice(1).join(" ")}</small></span></button><div className="event-card-body"><div className="card-topline"><span className={statusClass(event.status)}>{event.status}</span>{event.spots!==undefined&&<span className="spots"><Users size={15}/>{event.spots} Plätze frei</span>}</div><h3>{event.title}</h3><p><MapPin size={16}/>{event.place}</p><button className="text-link" onClick={()=>onSelect(event)}>Details ansehen <ArrowRight size={17}/></button></div></article>)}</div></section><section id="verein" className="club-strip"><div><span className="eyebrow light">SCHITEAM JULBACH</span><h2>Ehrenamtlich.<br/>Sportlich. Miteinander.</h2></div><p>Wir bringen Kinder, Jugendliche und Erwachsene mit Begeisterung in den Schnee – und schaffen Erlebnisse, die verbinden.</p></section></main>}

function EventDetail({event,back,signup}:{event:EventItem;back:()=>void;signup:()=>void}){const disabled=["Ausgebucht","Anmeldung geschlossen","Anmeldung startet bald"].includes(event.status);return <main className="detail-page"><button className="back-link" onClick={back}><ArrowLeft size={18}/> Alle Veranstaltungen</button><section className="detail-hero"><img src="/schiteam-momente.jpeg" alt="Schiteam Julbach beim Skifahren" style={{objectPosition:event.imagePosition}}/><div className="detail-overlay"><span className={statusClass(event.status)}>{event.status}</span><h1>{event.title}</h1><div className="detail-meta"><span><CalendarDays/>{event.dateLong}</span><span><MapPin/>{event.place}</span></div></div></section><section className="detail-layout"><article><span className="eyebrow">DARUM GEHT’S</span><h2>Gemeinsam besser Ski fahren.</h2><p>{event.description}</p><h3>Wichtige Informationen</h3><ul className="info-list">{event.info.map(i=><li key={i}><Check size={18}/>{i}</li>)}</ul></article><aside className="signup-box"><span className="eyebrow">ANMELDUNG</span><h3>{event.status==="Warteliste"?"Platz auf der Warteliste sichern":"Jetzt Platz sichern"}</h3><p>{event.status==="Warteliste"?"Neue Anmeldungen werden der Reihe nach auf die Warteliste gesetzt.":event.spots?`Aktuell sind noch ${event.spots} Plätze verfügbar.`:"Die Anmeldung ist derzeit nicht möglich."}</p><Button disabled={disabled} onClick={signup}>{event.status==="Warteliste"?"Für Warteliste anmelden":"Jetzt anmelden"}<ArrowRight/></Button><small>Die Anmeldung dauert ca. 2 Minuten.</small></aside></section></main>}

function Signup({event,back,submit}:{event:EventItem;back:()=>void;submit:()=>void}){return <main className="form-page"><button className="back-link" onClick={back}><ArrowLeft size={18}/> Zurück zur Veranstaltung</button><div className="form-header"><div><span className="eyebrow">ANMELDUNG</span><h1>{event.title}</h1><p><CalendarDays size={17}/>{event.dateLong}<span>·</span><MapPin size={17}/>{event.place}</p></div><span className={statusClass(event.status)}>{event.status}</span></div><form className="registration-form" onSubmit={e=>{e.preventDefault();submit()}}><section><FormTitle n="01" title="Teilnehmerdaten" text="Für wen ist die Anmeldung?"/><div className="fields two"><label>Vorname *<Input required placeholder="Vorname"/></label><label>Nachname *<Input required placeholder="Nachname"/></label><label>Geburtsjahr *<Input required inputMode="numeric" placeholder="z. B. 2016"/></label><label>Könnensstufe *<select required defaultValue=""><option value="" disabled>Bitte auswählen</option><option>Anfänger</option><option>Leicht fortgeschritten</option><option>Fortgeschritten</option></select></label></div></section><section><FormTitle n="02" title="Kontaktdaten" text="Wohin dürfen wir die Bestätigung senden?"/><div className="fields two"><label>E-Mail *<Input required type="email" placeholder="name@beispiel.at"/></label><label>Telefonnummer *<Input required type="tel" placeholder="+43 ..."/></label><label className="full">Anmerkung<Textarea placeholder="Allergien, wichtige Hinweise oder Fragen"/></label></div></section><section><div className="check-row"><Checkbox id="privacy" required/><label htmlFor="privacy">Ich stimme der Verarbeitung meiner Daten zur Durchführung der Veranstaltung zu. *</label></div><Button type="submit" size="lg">{event.status==="Warteliste"?"Auf Warteliste eintragen":"Anmeldung absenden"}<ArrowRight/></Button><p className="form-note"><LockKeyhole size={14}/> Deine Daten werden vertraulich behandelt.</p></section></form></main>}
function FormTitle({n,title,text}:{n:string;title:string;text:string}){return <div className="form-section-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Success({event,done}:{event:EventItem;done:()=>void}){const waiting=event.status==="Warteliste";return <main className="success-page"><div className={waiting?"success-icon waiting":"success-icon"}>{waiting?<Clock3/>:<Check/>}</div><span className="eyebrow">{waiting?"WARTELISTE":"ERFOLGREICH ANGEMELDET"}</span><h1>{waiting?"Du stehst auf der Warteliste.":"Schön, dass du dabei bist!"}</h1><p>{waiting?`Wir haben deine Anmeldung für ${event.title} aufgenommen. Sobald ein Platz frei wird, melden wir uns bei dir.`:`Deine Anmeldung für ${event.title} wurde erfolgreich aufgenommen.`}</p><div className="confirmation-card"><div><CalendarDays/><span><small>Termin</small>{event.dateLong}</span></div><div><MapPin/><span><small>Ort</small>{event.place}</span></div><div><Mail/><span><small>Bestätigung</small>Wird per E-Mail versendet</span></div></div><Button onClick={done}>Zur Veranstaltungsübersicht</Button></main>}
function Login({onLogin,onBack}:{onLogin:()=>void;onBack:()=>void}){return <main className="login-page"><button className="login-brand" onClick={onBack}><Brand/></button><section className="login-card"><div className="login-icon"><LockKeyhole/></div><span className="eyebrow">ADMINBEREICH</span><h1>Willkommen zurück</h1><p>Melde dich an, um Veranstaltungen und Anmeldungen zu verwalten.</p><form onSubmit={e=>{e.preventDefault();onLogin()}}><label>E-Mail-Adresse<Input required type="email" defaultValue="admin@schiteam-julbach.at"/></label><label>Passwort<Input required type="password" defaultValue="demopasswort"/></label><div className="login-options"><label><Checkbox/> Angemeldet bleiben</label><button type="button">Passwort vergessen?</button></div><Button type="submit">Anmelden <ArrowRight/></Button></form><small>Geschützter Bereich · Nur für berechtigte Bearbeiter</small></section><button className="back-link" onClick={onBack}><ArrowLeft size={17}/> Zur öffentlichen Seite</button></main>}

function AdminApp({selected,setSelected,tab,setTab,exit,notice,setNotice}:{selected:EventItem;setSelected:(e:EventItem)=>void;tab:AdminTab;setTab:(t:AdminTab)=>void;exit:()=>void;notice:string;setNotice:(s:string)=>void}){const[mobileSide,setMobileSide]=useState(false);const nav=[{id:"overview" as AdminTab,label:"Übersicht",icon:TicketCheck},{id:"participants" as AdminTab,label:"Teilnehmer",icon:Users,badge:"31"},{id:"settings" as AdminTab,label:"Einstellungen",icon:Settings},{id:"emails" as AdminTab,label:"E-Mails",icon:Mail},{id:"export" as AdminTab,label:"Excel-Export",icon:FileSpreadsheet}];return <div className="admin-shell"><aside className={mobileSide?"admin-sidebar open":"admin-sidebar"}><div className="sidebar-brand"><Brand compact/><button onClick={()=>setMobileSide(false)}><X/></button></div><div className="season-select"><small>AKTIVE SAISON</small><button>2026/27 <ChevronDown size={16}/></button></div><nav><small>VERWALTUNG</small><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><CalendarDays/> Veranstaltungen</button><button><Users/> Alle Anmeldungen <span>96</span></button><small>AKTUELLES EVENT</small>{nav.slice(1).map(({id,label,icon:Icon,badge})=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/>{label}{badge&&<span>{badge}</span>}</button>)}</nav><div className="sidebar-bottom"><button onClick={exit}><Eye/> Öffentliche Seite</button><div className="admin-user"><span>LN</span><p><strong>Lukas</strong><small>Administrator</small></p><MoreHorizontal/></div></div></aside><div className="admin-main"><header className="admin-header"><button className="sidebar-toggle" onClick={()=>setMobileSide(true)}><Menu/></button><div><span className="eyebrow">VERANSTALTUNG</span><div className="event-switcher"><h1>{selected.title}</h1><button><ChevronDown/></button></div></div><div className="admin-actions"><span className="save-state"><Check/> Gespeichert</span><Button variant="outline" onClick={exit}><Eye/> Vorschau</Button></div></header><div className="mobile-admin-tabs">{nav.map(({id,label})=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div><section className="admin-content">{notice&&<div className="notice"><Check/>{notice}<button onClick={()=>setNotice("")}><X/></button></div>}{tab==="overview"&&<Dashboard selected={selected} setSelected={setSelected} setTab={setTab}/>} {tab==="participants"&&<Participants setNotice={setNotice}/>} {tab==="settings"&&<EventSettings/>} {tab==="emails"&&<EmailSettings setNotice={setNotice}/>} {tab==="export"&&<ExportPanel setNotice={setNotice}/>}</section></div></div>}

function Dashboard({selected,setSelected,setTab}:{selected:EventItem;setSelected:(e:EventItem)=>void;setTab:(t:AdminTab)=>void}){const counts=[{label:"Bestätigt",value:"28",icon:UserCheck,tone:"red"},{label:"Warteliste",value:"3",icon:Clock3,tone:"orange"},{label:"Plätze frei",value:"12",icon:Users,tone:"dark"},{label:"Anmeldequote",value:"70%",icon:TicketCheck,tone:"gray"}];return <><div className="admin-title-row"><div><h2>Übersicht</h2><p>Alle wichtigen Zahlen und Veranstaltungen der Saison.</p></div><Button><Plus/> Neue Veranstaltung</Button></div><div className="stat-grid">{counts.map(({label,value,icon:Icon,tone})=><article key={label}><span className={`stat-icon ${tone}`}><Icon/></span><div><small>{label}</small><strong>{value}</strong></div></article>)}</div><div className="dashboard-grid"><section className="panel events-panel"><div className="panel-heading"><div><h3>Veranstaltungen</h3><p>Saison 2026/27</p></div><button><ListFilter/> Filtern</button></div><div className="admin-event-list">{events.map(event=><button key={event.id} className={event.id===selected.id?"selected":""} onClick={()=>setSelected(event)}><span className="mini-date">{event.date.split(" ")[0]}<small>{event.date.split(" ").slice(1).join(" ")}</small></span><span className="event-list-main"><strong>{event.title}</strong><small><MapPin/>{event.place}</small></span><span className={statusClass(event.status)}>{event.status}</span><span className="event-list-count"><Users/>{event.id===1?"28 / 40":event.status==="Warteliste"?"40 / 40":"–"}</span><MoreHorizontal/></button>)}</div></section><aside className="panel quick-panel"><div className="panel-heading"><div><h3>Schnellzugriff</h3><p>{selected.title}</p></div></div>{[["participants",Users,"Teilnehmer ansehen","28 bestätigt · 3 Warteliste"],["settings",Settings,"Event-Einstellungen","Zeitraum, Limit & Sichtbarkeit"],["emails",Mail,"E-Mail-Texte","Bestätigung & Warteliste"],["export",Download,"Excel exportieren","Felder individuell auswählen"]].map(([id,Icon,title,text])=><button key={String(id)} onClick={()=>setTab(id as AdminTab)}><Icon/><span><strong>{String(title)}</strong><small>{String(text)}</small></span><ArrowRight/></button>)}</aside></div></>}

function Participants({setNotice}:{setNotice:(s:string)=>void}){const[listTab,setListTab]=useState<"confirmed"|"wait">("confirmed"),data=listTab==="confirmed"?participants:waitlist;return <><div className="admin-title-row"><div><h2>Teilnehmer & Warteliste</h2><p>Anmeldungen verwalten und Personen manuell übernehmen.</p></div><Button><Plus/> Teilnehmer hinzufügen</Button></div><div className="list-toolbar"><div className="segmented"><button className={listTab==="confirmed"?"active":""} onClick={()=>setListTab("confirmed")}>Bestätigt <span>28</span></button><button className={listTab==="wait"?"active":""} onClick={()=>setListTab("wait")}>Warteliste <span>3</span></button></div><label className="search"><Search/><Input placeholder="Person suchen..."/></label><Button variant="outline"><ListFilter/> Filter</Button></div>{listTab==="wait"&&<div className="wait-hint"><Clock3/><div><strong>Warteliste nach Anmeldezeit sortiert</strong><p>Die Übernahme erfolgt bewusst manuell. Wähle eine Person aus, sobald ein Platz verfügbar ist.</p></div></div>}<div className="table-card"><div className="participant-table table-head"><Checkbox/><span>Name</span><span>Geburtsjahr</span><span>Anmeldung</span><span>Status</span><span></span></div>{data.map(person=><div className="participant-table" key={person.email}><Checkbox/><span className="person"><b>{person.name.split(" ").map(n=>n[0]).join("")}</b><span><strong>{person.name}</strong><small>{person.email}</small></span></span><span>{person.year}</span><span>{person.time}</span><span className={statusClass(person.status)}>{person.status}</span><span className="row-actions">{listTab==="wait"&&<Button size="sm" onClick={()=>setNotice(`${person.name} wurde in die Teilnehmerliste übernommen.`)}>Übernehmen</Button>}<button><MoreHorizontal/></button></span></div>)}</div></>}

function EventSettings(){return <><div className="admin-title-row"><div><h2>Event-Einstellungen</h2><p>Sichtbarkeit, Anmeldung, Teilnehmerlimit und Warteliste steuern.</p></div><Button>Änderungen speichern</Button></div><div className="settings-layout"><section className="panel settings-card"><h3>Sichtbarkeit & Anmeldung</h3><SettingRow icon={Eye} title="Öffentlich sichtbar" text="Die Veranstaltung wird auf der Website angezeigt." on/><SettingRow icon={TicketCheck} title="Anmeldung aktiv" text="Neue Anmeldungen sind möglich." on/><div className="date-settings"><label>Anmeldebeginn<Input type="datetime-local" defaultValue="2026-09-18T19:00"/></label><label>Anmeldeschluss<Input type="datetime-local" defaultValue="2026-12-20T23:59"/></label></div></section><section className="panel settings-card"><h3>Teilnehmer & Warteliste</h3><label className="limit-field">Maximale Teilnehmerzahl<Input type="number" defaultValue="40"/><small>Aktuell sind 28 von 40 Plätzen belegt.</small></label><SettingRow icon={Clock3} title="Warteliste aktivieren" text="Neue Anmeldungen landen nach Erreichen des Limits auf der Warteliste." on/><SettingRow icon={Users} title="Nur Warteliste" text="Alle neuen Anmeldungen direkt auf die Warteliste setzen."/><SettingRow icon={Eye} title="Verbleibende Plätze anzeigen" text="Freie Plätze öffentlich auf der Veranstaltungskarte anzeigen." on/></section></div></>}
function SettingRow({icon:Icon,title,text,on=false}:{icon:typeof Eye;title:string;text:string;on?:boolean}){return <div className="setting-row"><span><Icon/></span><div><strong>{title}</strong><p>{text}</p></div><Switch defaultChecked={on}/></div>}
function EmailSettings({setNotice}:{setNotice:(s:string)=>void}){const[emailTab,setEmailTab]=useState<"success"|"wait">("success");const body=emailTab==="success"?`Hallo {{vorname}} {{nachname}},\n\ndeine Anmeldung für {{veranstaltung}} am {{datum}} war erfolgreich.\n\nSchiteam Julbach`:`Hallo {{vorname}} {{nachname}},\n\ndeine Anmeldung für {{veranstaltung}} am {{datum}} wurde aufgenommen. Du befindest dich derzeit auf der Warteliste.\n\nSchiteam Julbach`;return <><div className="admin-title-row"><div><h2>E-Mail-Einstellungen</h2><p>Automatische Nachrichten für Anmeldung und Warteliste bearbeiten.</p></div><Button onClick={()=>setNotice("E-Mail-Vorlagen wurden gespeichert.")}>Vorlagen speichern</Button></div><div className="connection-card"><div className="gmail-badge">M</div><div><strong>Gmail-Konto</strong><p>Bereit für die spätere Verknüpfung mit dem Vereinskonto.</p></div><span className="connection-state"><span/> Noch nicht verbunden</span><Button variant="outline">Gmail verbinden</Button></div><div className="email-layout"><aside><button className={emailTab==="success"?"active":""} onClick={()=>setEmailTab("success")}><Check/>Anmeldung erfolgreich</button><button className={emailTab==="wait"?"active":""} onClick={()=>setEmailTab("wait")}><Clock3/>Warteliste</button><div className="placeholder-box"><strong>Verfügbare Platzhalter</strong>{["{{vorname}}","{{nachname}}","{{veranstaltung}}","{{datum}}"].map(p=><code key={p}>{p}</code>)}</div></aside><section className="panel email-editor"><label>Betreff<Input defaultValue={emailTab==="success"?"Anmeldung erfolgreich – {{veranstaltung}}":"Warteliste – {{veranstaltung}}"}/></label><label>Nachricht<Textarea rows={10} value={body} readOnly/></label><p><Mail/> Wird automatisch nach der Anmeldung versendet.</p></section></div></>}
function ExportPanel({setNotice}:{setNotice:(s:string)=>void}){const fields=["Vorname","Nachname","E-Mail","Telefonnummer","Geburtsjahr","Könnensstufe","Teilnehmerstatus","Anmeldezeitpunkt","Anmerkung"];return <><div className="admin-title-row"><div><h2>Excel-Export</h2><p>Wähle Status und Felder für deine individuelle Teilnehmerliste.</p></div></div><div className="export-layout"><section className="panel export-card"><FormTitle n="01" title="Daten auswählen" text="Welche Personen sollen exportiert werden?"/><div className="radio-cards">{[[Users,"Alle Anmeldungen","31 Personen"],[UserCheck,"Nur Bestätigte","28 Personen"],[Clock3,"Nur Warteliste","3 Personen"]].map(([Icon,title,text],i)=><label key={String(title)}><input type="radio" name="group" defaultChecked={i===0}/><span><Icon/><strong>{String(title)}</strong><small>{String(text)}</small></span></label>)}</div><FormTitle n="02" title="Felder festlegen" text="Diese Spalten werden in Excel übernommen."/><div className="field-checkboxes">{fields.map((field,i)=><label key={field}><Checkbox defaultChecked={i<8}/>{field}</label>)}</div></section><aside className="panel export-summary"><span className="excel-icon"><FileSpreadsheet/></span><h3>Export bereit</h3><p>Kinderskikurs – Gruppe 1</p><dl><div><dt>Datensätze</dt><dd>31</dd></div><div><dt>Spalten</dt><dd>8</dd></div><div><dt>Format</dt><dd>.xlsx</dd></div></dl><Button onClick={()=>setNotice("Excel-Export wurde vorbereitet. Die echte Datei wird nach Backend-Anbindung erzeugt.")}><Download/> Excel herunterladen</Button><small>Der Export berücksichtigt deine aktuelle Auswahl.</small></aside></div></>}
