'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {workbook} from '@/lib/export-xlsx';
export function ParticipantEditor({person,event,busy,save,cancel}:{person:any;event:any;busy:boolean;save:(p:any)=>void;cancel:()=>void}){return <form className="panel settings-card" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);save({...person,eventId:event.id,firstName:form.get('firstName'),lastName:form.get('lastName'),birthDate:form.get('birthDate'),skill:form.get('skill'),email:form.get('email'),phone:form.get('phone'),note:form.get('note'),status:form.get('status'),consent:form.get('consent')==='on'});}}><h3>{person.id?'Teilnehmer bearbeiten':'Teilnehmer hinzufügen'}</h3><div className="fields two">{[['firstName','first_name','Vorname','text'],['lastName','last_name','Nachname','text'],['birthDate','birth_date','Geburtsdatum','date'],['email','email','E-Mail','email'],['phone','phone','Telefon','tel']].map(([name,key,label,type])=><label key={name}>{label}<Input name={name} type={type} defaultValue={person[key]||''} required/></label>)}<label>Könnensstufe<select name="skill" defaultValue={person.skill||event.skillLevels[0]}>{event.skillLevels.map((s:string)=><option key={s}>{s}</option>)}</select></label><label>Status<select name="status" defaultValue={person.status||'confirmed'}><option value="confirmed">Bestätigt</option><option value="waitlist">Warteliste</option></select></label><label>Anmerkung<Textarea name="note" defaultValue={person.note||''}/></label></div>{!person.id&&<label className="check-row"><input name="consent" type="checkbox" required/> Die Zustimmung zur Anmeldung und Datenverarbeitung liegt vor.</label>}<div><Button disabled={busy}>Speichern</Button> <Button type="button" variant="outline" onClick={cancel}>Abbrechen</Button></div></form>}
const columns=[['first_name','Vorname'],['last_name','Nachname'],['email','E-Mail'],['phone','Telefonnummer'],['birth_date','Geburtsdatum'],['skill','Könnensstufe'],['status','Teilnehmerstatus'],['created_at','Anmeldezeitpunkt'],['note','Anmerkung']];
export function ExportView({event,people}:{event:any;people:any[]}){const[status,setStatus]=useState('all'),[fields,setFields]=useState(columns.slice(0,8).map(c=>c[0]));const selected=columns.filter(c=>fields.includes(c[0]));const rows=people.filter(p=>p.event_id===event?.id&&(status==='all'||p.status===status));return <section className="panel settings-card"><h2>Excel-Export</h2><p>{event?.title}</p><label>Personen<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Alle Anmeldungen</option><option value="confirmed">Nur Bestätigte</option><option value="waitlist">Nur Warteliste</option></select></label><div className="field-checkboxes">{columns.map(([key,label])=><label key={key}><input type="checkbox" checked={fields.includes(key)} onChange={e=>setFields(e.target.checked?[...fields,key]:fields.filter(f=>f!==key))}/>{label}</label>)}</div><p>{rows.length} Datensätze · {selected.length} Spalten</p><Button disabled={!selected.length} onClick={()=>{const content=workbook([selected.map(c=>c[1]),...rows.map(p=>selected.map(([key])=>key==='status'?(p[key]==='confirmed'?'Bestätigt':'Warteliste'):p[key]))]);const url=URL.createObjectURL(new Blob([new Uint8Array(content)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const link=document.createElement('a');link.href=url;link.download=`teilnehmer-${event.id}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Excel herunterladen</Button></section>}
export function EventImage({initial}:{initial:string}){const[url,setUrl]=useState(initial||'/schiteam-momente.jpeg'),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <><h3>Veranstaltungsbild</h3><img src={url} alt="Vorschau" style={{width:'100%',maxHeight:240,objectFit:'cover'}}/><label>Bild-URL<Input name="imageUrl" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Bild hochladen (PNG, JPEG, WebP, bis 5 MB)<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5000000){setError('Bitte ein Bild bis 5 MB auswählen.');return;}setBusy(true);setError('');try{const form=new FormData();form.append('image',file);const response=await fetch('/api/platform',{method:'POST',body:form});const data:any=await response.json();if(!response.ok)throw new Error(data.error);setUrl(data.url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{busy&&<p>Bild wird hochgeladen. Bitte vor dem Speichern warten.</p>}{error&&<p role="alert">{error}</p>}<p>Mit „Änderungen speichern“ wird das Bild der Veranstaltung zugeordnet.</p></>}
