'use client';
import {Image as ImageIcon,Upload} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
export function ParticipantEditor({person,event,busy,save,cancel}:{person:any;event:any;busy:boolean;save:(p:any)=>void;cancel:()=>void}){return <form className="panel settings-card" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);save({...person,eventId:event.id,firstName:form.get('firstName'),lastName:form.get('lastName'),birthDate:form.get('birthDate'),skill:form.get('skill'),email:form.get('email'),phone:form.get('phone'),address:form.get('address'),postalCode:form.get('postalCode'),city:form.get('city'),note:form.get('note'),adminNote:form.get('adminNote'),osvMember:form.get('osvMember')===''?null:form.get('osvMember')==='yes',status:form.get('status'),consent:form.get('consent')==='on'});}}><h3>{person.id?'Teilnehmer bearbeiten':'Teilnehmer hinzufügen'}</h3><div className="fields two">{[['firstName','first_name','Vorname','text'],['lastName','last_name','Nachname','text'],['birthDate','birth_date','Geburtsdatum','date'],['email','email','E-Mail','email'],['phone','phone','Telefon','tel']].map(([name,key,label,type])=><label key={name}>{label}<Input name={name} type={type} defaultValue={person[key]||''} required/></label>)}<label>Adresse (Straße und Hausnummer)<Input name="address" defaultValue={person.address||''} required={!person.id} maxLength={200}/></label><label>PLZ<Input name="postalCode" defaultValue={person.postal_code||''} required={!person.id} maxLength={12}/></label><label>Ort<Input name="city" defaultValue={person.city||''} required={!person.id} maxLength={200}/></label><label>Könnensstufe<select name="skill" defaultValue={person.skill||event.skillLevels[0]}>{event.skillLevels.map((s:string)=><option key={s}>{s}</option>)}</select></label><label>ÖSV-Mitglied<select name="osvMember" required={!person.id} defaultValue={person.osv_member==null?"":person.osv_member?"yes":"no"}><option value="" disabled>Bitte auswählen</option><option value="yes">Ja</option><option value="no">Nein</option></select></label><label>Status<select name="status" defaultValue={person.status||'confirmed'}><option value="confirmed">Bestätigt</option><option value="waitlist">Warteliste</option></select></label><label>Bemerkung für den Admin<Textarea name="adminNote" maxLength={3000} defaultValue={person.admin_note||''}/></label><label>Anmerkung der Anmeldung<Textarea name="note" defaultValue={person.note||''}/></label></div>{!person.id&&<label className="check-row"><input name="consent" type="checkbox" required/> Die Zustimmung zur Anmeldung und Datenverarbeitung liegt vor.</label>}<div><Button disabled={busy}>Speichern</Button> <Button type="button" variant="outline" onClick={cancel}>Abbrechen</Button></div></form>}
const imageSize=800;

async function prepareImage(file:File,variant:'logo'|'photo'){
  const source=await createImageBitmap(file),canvas=document.createElement('canvas'),context=canvas.getContext('2d');
  if(!context){source.close();throw new Error('Das Bild konnte nicht verarbeitet werden.');}
  canvas.width=variant==='photo'?600:imageSize;canvas.height=imageSize;
  const scale=variant==='photo'?Math.max(canvas.width/source.width,canvas.height/source.height):Math.min(canvas.width/source.width,canvas.height/source.height),width=Math.round(source.width*scale),height=Math.round(source.height*scale);
  context.clearRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';
  context.drawImage(source,Math.round((canvas.width-width)/2),Math.round((canvas.height-height)/2),width,height);source.close();
  const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Das Bild konnte nicht verarbeitet werden.')),'image/png'));
  return new File([blob],`${file.name.replace(/\.[^.]+$/,'')||'bild'}-${canvas.width}x${canvas.height}.png`,{type:'image/png'});
}

function ImageUpload({initial,fallback='',name,onChange,alt,variant='logo'}:{initial:string;fallback?:string;name?:string;onChange?:(url:string)=>void;alt:string;variant?:'logo'|'photo'}){
  const[url,setUrl]=useState(initial||fallback),[preview,setPreview]=useState(initial||fallback),[error,setError]=useState(''),[busy,setBusy]=useState(false),previewObject=useRef('');
  useEffect(()=>()=>{if(previewObject.current)URL.revokeObjectURL(previewObject.current)},[]);
  const upload=async(file?:File)=>{if(!file)return;setBusy(true);setError('');const previous=url;try{const resized=await prepareImage(file,variant);if(previewObject.current)URL.revokeObjectURL(previewObject.current);previewObject.current=URL.createObjectURL(resized);setPreview(previewObject.current);const form=new FormData();form.append('image',resized);const response=await fetch('/api/platform',{method:'POST',body:form});const data:any=await response.json();if(!response.ok)throw new Error(data.error||'Upload fehlgeschlagen.');setUrl(data.url);setPreview(data.url);onChange?.(data.url);}catch(e){setPreview(previous||fallback);setError((e as Error).message);}finally{setBusy(false)}};
  return <div className={`image-upload-control ${variant==='photo'?'portrait-upload':''}`}>{preview?<img src={preview} alt={alt}/>:<div className="sponsor-logo-placeholder"><ImageIcon/><span>{variant==='photo'?'Foto':'Logo'}</span></div>}<div className="image-upload-actions">{name?<input type="hidden" name={name} value={url}/>:null}<label className="image-upload-button" aria-disabled={busy}><Upload/>{busy?'Wird hochgeladen …':'Bild hochladen'}<input className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label>{variant==='photo'?<small>Hochformat 3:4</small>:<small>Automatisch auf 800 × 800 Pixel angepasst.</small>}{error?<small role="alert">{error}</small>:null}</div></div>;
}

export function EventImage({initial}:{initial:string}){return <><h3><ImageIcon/> Veranstaltungsbild</h3><ImageUpload initial={initial} fallback="/schiteam-momente.jpeg" name="imageUrl" alt="Vorschau des Veranstaltungsbildes"/></>}

export function SponsorLogoUpload({name,initial,onChange}:{name:string;initial:string;onChange:(url:string)=>void}){return <ImageUpload initial={initial} onChange={onChange} alt={`Logo-Vorschau von ${name||'Sponsor'}`}/>}

export function BoardPhotoUpload({name,initial,onChange}:{name:string;initial:string;onChange:(url:string)=>void}){return <ImageUpload variant="photo" initial={initial} onChange={onChange} alt={`Foto-Vorschau von ${name||'Vorstandsmitglied'}`}/>}
