// Idempotent initial schema for a new Neon/Postgres database.
export const schemaSql = `
CREATE TABLE IF NOT EXISTS events (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 data text NOT NULL, capacity integer NOT NULL DEFAULT 40,
 active integer NOT NULL DEFAULT 1, visible integer NOT NULL DEFAULT 1,
 waitlist integer NOT NULL DEFAULT 1, only_waitlist integer NOT NULL DEFAULT 0,
 starts text NOT NULL DEFAULT '', ends text NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS registrations (
 id text PRIMARY KEY, event_id integer NOT NULL REFERENCES events(id),
 first_name text NOT NULL, last_name text NOT NULL, birth_date text NOT NULL,
 skill text NOT NULL, email text NOT NULL, phone text NOT NULL,
 note text NOT NULL DEFAULT '', address text NOT NULL DEFAULT '',
 postal_code text NOT NULL DEFAULT '', city text NOT NULL DEFAULT '',
 osv_member integer, admin_note text NOT NULL DEFAULT '',
 status text NOT NULL, consent_at text NOT NULL, created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_registrations_event_status ON registrations(event_id,status);
CREATE TABLE IF NOT EXISTS sessions (hash text PRIMARY KEY, expires bigint NOT NULL, version text NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts (key text PRIMARY KEY, count integer NOT NULL, expires bigint NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS images (
 id text PRIMARY KEY,
 content_type text NOT NULL,
 data text NOT NULL,
 created_at text NOT NULL
);
`;
