import { registrationWindow, isLocalAddress } from '@/lib/registration-rules';
import { putImage } from '@/lib/server-storage';
export const runtime = 'nodejs';
import { database, adminPassword } from '@/lib/server-db';
import { initialEvents } from '@/lib/initial-events';
import { defaultEventDescription, defaultEventInfo } from '@/lib/event-defaults';
import { z } from 'zod';
export const dynamic='force-dynamic';
const cookieName='julbach_admin';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function admin(request:Request){const token=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!token)return false;const row=await database().prepare('SELECT expires,version FROM sessions WHERE hash=?').bind(await hash(token)).first<{expires:number;version:string}>();return !!row&&row.expires>Date.now()&&row.version===await hash(adminPassword());}
const eventDefaultsMigrationKey='event_defaults_2026_10_01';
async function seed(){
 const db=database();
 const initialized=await db.prepare("SELECT value FROM settings WHERE key='initialized'").first();
 if(!initialized){
  await db.batch([...initialEvents.map(e=>db.prepare("INSERT INTO events (id,data,capacity,active,visible,waitlist,only_waitlist,starts,ends) SELECT ?,?,?,?,1,1,?,'','' WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='initialized') ON CONFLICT DO NOTHING").bind(e.id,JSON.stringify(e),40,['Anmeldung geschlossen','Anmeldung startet bald','Ausgebucht'].includes(e.status)?0:1,e.status==='Warteliste'?1:0)),...Array.from({length:10},(_,index)=>{const n=String(index+1).padStart(2,'0'),now=new Date().toISOString();return db.prepare("INSERT INTO registrations (id,event_id,first_name,last_name,birth_date,skill,email,phone,note,status,consent_at,created_at) SELECT ?,1,?,?,'2016-01-01',?,?,'0000000000','Fiktiver Testdatensatz – keine echte Anmeldung','confirmed',?,? WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='initialized') ON CONFLICT DO NOTHING").bind('00000000-0000-4000-8000-'+String(index+1).padStart(12,'0'),'Testperson',n,initialEvents[0].skillLevels[index%initialEvents[0].skillLevels.length],'test'+n+'@example.invalid',now,now)}),db.prepare("INSERT INTO settings (key,value) VALUES ('initialized','1') ON CONFLICT DO NOTHING"),db.prepare("INSERT INTO settings (key,value) VALUES (?, '1') ON CONFLICT DO NOTHING").bind(eventDefaultsMigrationKey),db.prepare("SELECT setval(pg_get_serial_sequence('events','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM events),1))")]);
  return;
 }
 if(await db.prepare('SELECT value FROM settings WHERE key=?').bind(eventDefaultsMigrationKey).first())return;
 const row=await db.prepare('SELECT data FROM events WHERE id=1').first<{data:string}>();
 const statements=[];
 if(row){const event={...JSON.parse(row.data),description:defaultEventDescription,info:[...defaultEventInfo]};statements.push(db.prepare('UPDATE events SET data=? WHERE id=1').bind(JSON.stringify(event)));}
 statements.push(db.prepare("INSERT INTO settings (key,value) VALUES (?, '1') ON CONFLICT DO NOTHING").bind(eventDefaultsMigrationKey));
 await db.batch(statements);
}
async function eventList(all=false){const rows=await database().prepare(`SELECT e.*, (SELECT COUNT(*) FROM registrations r WHERE r.event_id=e.id AND r.status='confirmed') AS confirmed, (SELECT COUNT(*) FROM registrations r WHERE r.event_id=e.id AND r.status='waitlist') AS waiting FROM events e ${all?'':'WHERE e.visible=1'} ORDER BY e.id`).all<any>();const events=rows.results.map(row=>{const data=JSON.parse(row.data),remaining=Math.max(0,row.capacity-row.confirmed),now=new Date().toISOString();let status='Anmeldung offen';const window=registrationWindow({active:!!row.active,starts:row.starts,ends:row.ends},Date.parse(now));if(window.before&&(window.scheduled||row.active))status='Anmeldung startet bald';else if(!window.active)status='Anmeldung geschlossen';else if(data.manualWaitlist)status='Warteliste';else if(!remaining)status=row.waitlist||row.only_waitlist?'Warteliste':'Ausgebucht';return {...data,id:row.id,capacity:row.capacity,active:!!row.active,registrationActive:window.active,scheduled:window.scheduled,visible:!!row.visible,waitlist:!!row.waitlist,manualWaitlist:!!data.manualWaitlist,onlyWaitlist:!!row.only_waitlist,starts:row.starts,ends:row.ends,confirmed:Number(row.confirmed),waiting:Number(row.waiting),spots:remaining,status};});return events.sort((left,right)=>{const leftDate=typeof left.eventStartDate==='string'?left.eventStartDate:'',rightDate=typeof right.eventStartDate==='string'?right.eventStartDate:'';if(leftDate&&rightDate)return leftDate.localeCompare(rightDate)||left.id-right.id;if(leftDate)return -1;if(rightDate)return 1;return left.id-right.id;});}
export async function GET(request:Request){try{await seed();const db=database();const [legalRow,sponsorRow,boardRow]=await Promise.all([db.prepare("SELECT value FROM settings WHERE key='legal'").first<{value:string}>(),db.prepare("SELECT value FROM settings WHERE key='sponsors'").first<{value:string}>(),db.prepare("SELECT value FROM settings WHERE key='board'").first<{value:string}>()]);const legal=legalRow?JSON.parse(legalRow.value):{privacy:'',imprint:''};const sponsors=sponsorRow?JSON.parse(sponsorRow.value):[];const board=boardRow?JSON.parse(boardRow.value):[];const url=new URL(request.url);if(url.searchParams.get('admin')==='1'){if(!await admin(request))return json({error:'Bitte als Administrator anmelden.'},401);const [events,registrations,settings]=await Promise.all([eventList(true),db.prepare('SELECT * FROM registrations ORDER BY created_at,id').all(),db.prepare("SELECT value FROM settings WHERE key='emails'").first<{value:string}>()]);return json({legal,sponsors,board,events,registrations:registrations.results,emails:settings?JSON.parse(settings.value):{success:'Hallo {{vorname}}, deine Anmeldung für {{veranstaltung}} wurde gespeichert.',wait:'Hallo {{vorname}}, du stehst auf der Warteliste für {{veranstaltung}}.'}});}return json({legal,sponsors,board,events:await eventList()});}catch(error){console.error('Database read failed',error);return json({error:'Die Daten konnten nicht geladen werden. Bitte erneut versuchen.'},503);}}
const text=z.string().trim().min(1).max(200);
const registration=z.object({requestId:z.string().uuid(),eventId:z.number().int().positive(),firstName:text,lastName:text,birthDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v<=new Date().toISOString().slice(0,10)&&v>='1900-01-01'),skill:text,email:z.string().trim().email().max(254),phone:z.string().trim().min(3).max(60),address:text,postalCode:z.string().trim().min(1).max(12),city:text,note:z.string().max(3000).default(''),osvMember:z.boolean(),consent:z.literal(true)});
const storedRegistration=registration.extend({osvMember:z.boolean().nullable().default(null),address:z.string().trim().max(200).default(''),postalCode:z.string().trim().max(12).default(''),city:z.string().trim().max(200).default('')});
const dateTime=z.string().max(40).refine(v=>!v||!isNaN(Date.parse(v))).transform(v=>v?new Date(v).toISOString():'');
const eventDay=z.string().refine(v=>!v||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v+'T12:00:00').toISOString().slice(0,10)===v));
const eventSchema=z.object({id:z.number().int().positive().optional(),title:text,detailHeading:text.default("Gemeinsam besser Ski fahren."),date:text,dateLong:text,eventDateMode:z.enum(['single','range']).default('single'),eventStartDate:eventDay.default(''),eventEndDate:eventDay.default(''),place:text,description:z.string().max(10000),info:z.array(z.string().max(500)).max(30),registrationInfo:z.string().max(5000),skillLevels:z.array(text).min(1).max(30),imagePosition:z.string().max(50).default('50% 50%'),imageUrl:z.string().max(2000).refine(v=>!v||v.startsWith('/api/images?key=')||v==='/schiteam-momente.jpeg'||/^https:\/\//.test(v)).default(''),showSpots:z.boolean().default(true),capacity:z.number().int().min(1).max(100000),active:z.boolean(),visible:z.boolean(),waitlist:z.boolean(),manualWaitlist:z.boolean().default(false),onlyWaitlist:z.boolean(),starts:dateTime,ends:dateTime}).refine(v=>v.eventDateMode==='single'?((!v.eventStartDate&&!v.eventEndDate)||v.eventEndDate===v.eventStartDate):!!v.eventStartDate&&!!v.eventEndDate&&v.eventEndDate>=v.eventStartDate,{message:'Veranstaltungstermin prüfen'}).refine(v=>(!v.starts||!isNaN(Date.parse(v.starts)))&&(!v.ends||!isNaN(Date.parse(v.ends)))&&(!v.starts||!v.ends||v.starts<v.ends),{message:'Anmeldezeitraum prüfen'});
const sponsorSchema=z.object({id:z.string().uuid(),name:text,logoUrl:z.string().max(2000).refine(v=>!v||v.startsWith('/api/images?key=')||/^https:\/\//.test(v))});
const boardMemberSchema=z.object({id:z.string().uuid(),name:text,role:text,qualifications:z.array(z.string().trim().max(500)).max(30).default([]).transform(values=>values.filter(Boolean)),photoUrl:z.string().max(2000).refine(v=>!v||v.startsWith('/api/images?key=')||/^https:\/\//.test(v))});
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)return json({error:'Ungültige Anfrage.'},403);if(request.headers.get('content-type')?.includes('multipart/form-data')){if(!await admin(request))return json({error:'Bitte anmelden.'},401);if(Number(request.headers.get('content-length')||0)>4200000)return json({error:'Bild maximal 4 MB.'},413);const form=await request.formData();const file=form.get('image');if(!(file instanceof File)||file.size>4000000)return json({error:'Bitte ein Bild bis 4 MB auswählen.'},400);const bytes=new Uint8Array(await file.arrayBuffer());let type='';if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)type='image/png';else if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)type='image/jpeg';else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')type='image/webp';if(!type)return json({error:'Bitte PNG, JPEG oder WebP auswählen.'},400);const key=crypto.randomUUID();await putImage(key,bytes,type);return json({url:'/api/images?key='+key});}if(!request.headers.get('content-type')?.includes('application/json'))return json({error:'JSON erwartet.'},415);const raw=await request.text();if(raw.length>30000)return json({error:'Anfrage zu groß.'},413);const body=JSON.parse(raw);const db=database();
if(body.action==='login'){const key=await hash((process.env.VERCEL === '1' ? request.headers.get('x-vercel-forwarded-for') : null)||'shared');const now=Date.now();const attempt=await db.prepare('INSERT INTO login_attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN login_attempts.expires<? THEN 1 ELSE login_attempts.count+1 END, expires=CASE WHEN login_attempts.expires<? THEN excluded.expires ELSE login_attempts.expires END RETURNING count').bind(key,now+900000,now,now).first<{count:number}>();if(attempt&&attempt.count>10)return json({error:'Zu viele Anmeldeversuche. Bitte in 15 Minuten erneut versuchen.'},429);if(body.username!=='admin'||typeof body.password!=='string'||await hash(body.password)!==await hash(adminPassword()))return json({error:'Benutzername oder Passwort ist falsch.'},401);const token=crypto.randomUUID()+crypto.randomUUID();await db.batch([db.prepare('DELETE FROM sessions WHERE expires<?').bind(now),db.prepare('INSERT INTO sessions (hash,expires,version) VALUES (?,?,?)').bind(await hash(token),now+28800000,await hash(adminPassword())),db.prepare('DELETE FROM login_attempts WHERE key=?').bind(key)]);const response=json({ok:true});response.headers.set('Set-Cookie',`${cookieName}=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${new URL(request.url).protocol==='https:'?'; Secure':''}`);return response;}
if(body.action==='logout'){const token=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(token)await db.prepare('DELETE FROM sessions WHERE hash=?').bind(await hash(token)).run();const response=json({ok:true});response.headers.set('Set-Cookie',`${cookieName}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0`);return response;}
if(body.action==='register'){
 const input=registration.parse(body);const event=(await eventList()).find(e=>e.id===input.eventId);
 if(!event||!event.skillLevels.includes(input.skill))return json({error:'Veranstaltung oder Könnensstufe ungültig.'},400);
 const now=new Date().toISOString();const external=Number(!isLocalAddress(input.postalCode,input.city)),manualWaitlist=Number(!!event.manualWaitlist);
 const result=await db.prepare(`INSERT INTO registrations (id,event_id,first_name,last_name,birth_date,skill,email,phone,note,address,postal_code,city,osv_member,status,consent_at,created_at)
 SELECT ?,id,?,?,?,?,?,?,?,?,?,?,?,CASE WHEN ?=1 OR (only_waitlist=1 AND ?=1) OR (SELECT COUNT(*) FROM registrations WHERE event_id=events.id AND status='confirmed')>=capacity THEN 'waitlist' ELSE 'confirmed' END,?,?
 FROM events WHERE id=? AND visible=1 AND ((starts<>'' AND ends<>'') OR active=1) AND (starts='' OR starts<=?) AND (ends='' OR ends>?)
 AND (?=1 OR (only_waitlist=1 AND ?=1) OR (SELECT COUNT(*) FROM registrations WHERE event_id=events.id AND status='confirmed')<capacity OR waitlist=1)
 ON CONFLICT(id) DO NOTHING RETURNING status`).bind(input.requestId,input.firstName,input.lastName,input.birthDate,input.skill,input.email,input.phone,input.note,input.address,input.postalCode,input.city,Number(input.osvMember),manualWaitlist,external,now,now,input.eventId,now,now,manualWaitlist,external).first<{status:string}>();
 if(result)return json({ok:true,status:result.status});const previous=await db.prepare('SELECT status FROM registrations WHERE id=? AND event_id=? AND email=?').bind(input.requestId,input.eventId,input.email).first<{status:string}>();return previous?json({ok:true,status:previous.status}):json({error:'Die Anmeldung ist geschlossen oder alle Plätze sind vergeben.'},409);
}
if(!await admin(request))return json({error:'Bitte als Administrator anmelden.'},401);
if(body.action==='saveEvent'){const event=eventSchema.parse(body.event);const values=[JSON.stringify(event),event.capacity,Number(event.active),Number(event.visible),Number(event.waitlist),Number(event.onlyWaitlist),event.starts,event.ends];if(event.id)await db.prepare('UPDATE events SET data=?,capacity=?,active=?,visible=?,waitlist=?,only_waitlist=?,starts=?,ends=? WHERE id=?').bind(...values,event.id).run();else await db.prepare('INSERT INTO events (data,capacity,active,visible,waitlist,only_waitlist,starts,ends) VALUES (?,?,?,?,?,?,?,?)').bind(...values).run();return json({ok:true});}
if(body.action==='saveSponsors'){const sponsors=z.array(sponsorSchema).max(60).parse(body.sponsors);await db.prepare("INSERT INTO settings (key,value) VALUES ('sponsors',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(sponsors)).run();return json({ok:true});}
if(body.action==='saveBoard'){const board=z.array(boardMemberSchema).max(60).parse(body.board);await db.prepare("INSERT INTO settings (key,value) VALUES ('board',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(board)).run();return json({ok:true});}
if(body.action==='promote'){const id=z.string().uuid().parse(body.id);const row=await db.prepare("UPDATE registrations SET status='confirmed' WHERE id=? AND status='waitlist' AND (SELECT COUNT(*) FROM registrations r WHERE r.event_id=registrations.event_id AND r.status='confirmed')<(SELECT capacity FROM events WHERE id=registrations.event_id) RETURNING id").bind(id).first();return row?json({ok:true}):json({error:'Kein freier Platz vorhanden oder Person bereits übernommen.'},409);}
if(body.action==='saveParticipant'){const input=(body.person.id?storedRegistration:registration).parse({...body.person,requestId:body.person.id||crypto.randomUUID(),consent:body.person.id?true:body.person.consent});const id=body.person.id?z.string().uuid().parse(body.person.id):input.requestId;const status=z.enum(['confirmed','waitlist']).parse(body.person.status);const adminNote=z.string().max(3000).default('').parse(body.person.adminNote);const osvMember=input.osvMember===null?null:Number(input.osvMember);const event=(await eventList(true)).find(e=>e.id===input.eventId);if(!event||!event.skillLevels.includes(input.skill))return json({error:'Könnensstufe oder Veranstaltung ungültig.'},400);const now=new Date().toISOString();let result;if(body.person.id){result=await db.prepare("UPDATE registrations SET first_name=?,last_name=?,birth_date=?,skill=?,email=?,phone=?,note=?,address=?,postal_code=?,city=?,osv_member=?,admin_note=?,status=? WHERE id=? AND event_id=? AND (?='waitlist' OR (SELECT COUNT(*) FROM registrations r WHERE r.event_id=registrations.event_id AND r.status='confirmed' AND r.id<>?)<(SELECT capacity FROM events WHERE id=registrations.event_id)) RETURNING id").bind(input.firstName,input.lastName,input.birthDate,input.skill,input.email,input.phone,input.note,input.address,input.postalCode,input.city,osvMember,adminNote,status,id,input.eventId,status,id).first();}else{result=await db.prepare("INSERT INTO registrations (id,event_id,first_name,last_name,birth_date,skill,email,phone,note,address,postal_code,city,osv_member,admin_note,status,consent_at,created_at) SELECT ?,id,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM events WHERE id=? AND (?='waitlist' OR (SELECT COUNT(*) FROM registrations WHERE event_id=events.id AND status='confirmed')<capacity) RETURNING id").bind(id,input.firstName,input.lastName,input.birthDate,input.skill,input.email,input.phone,input.note,input.address,input.postalCode,input.city,osvMember,adminNote,status,now,now,input.eventId,status).first();}return result?json({ok:true}):json({error:'Kein freier Platz vorhanden oder Anmeldung nicht gefunden.'},409);}
if(body.action==='deleteParticipant'){await db.prepare('DELETE FROM registrations WHERE id=?').bind(z.string().uuid().parse(body.id)).run();return json({ok:true});}
if(body.action==='saveLegal'){const field=z.enum(['privacy','imprint']).parse(body.field);const content=z.string().max(20000).parse(body.content);await db.prepare("INSERT INTO settings (key,value) VALUES ('legal',jsonb_build_object(?::text,?::text)::text) ON CONFLICT(key) DO UPDATE SET value=jsonb_set(settings.value::jsonb, ARRAY[?::text], to_jsonb(?::text))::text").bind(field,content,field,content).run();return json({ok:true});}
if(body.action==='saveEmails'){const emails=z.object({success:z.string().max(10000),wait:z.string().max(10000),successSubject:z.string().max(300).optional(),waitSubject:z.string().max(300).optional()}).parse(body.emails);await db.prepare("INSERT INTO settings (key,value) VALUES ('emails',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(emails)).run();return json({ok:true});}
return json({error:'Unbekannte Aktion.'},400);
}catch(error){if(error instanceof z.ZodError||error instanceof SyntaxError)return json({error:'Bitte alle Eingaben und den Anmeldezeitraum prüfen.'},400);console.error('Database write failed',error);return json({error:'Speichern fehlgeschlagen. Deine Eingaben bleiben erhalten. Bitte erneut versuchen.'},503);}}
