import { env } from 'cloudflare:workers';
import { database, adminPassword } from '@/lib/server-db';
import { initialEvents } from '@/lib/initial-events';
import { z } from 'zod';
export const dynamic='force-dynamic';
const cookieName='julbach_admin';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function admin(request:Request){const token=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!token)return false;const row=await database().prepare('SELECT expires,version FROM sessions WHERE hash=?').bind(await hash(token)).first<{expires:number;version:string}>();return !!row&&row.expires>Date.now()&&row.version===await hash(adminPassword());}
async function seed(){const db=database();await db.batch([...initialEvents.map(e=>db.prepare("INSERT OR IGNORE INTO events (id,data,capacity,active,visible,waitlist,only_waitlist,starts,ends) SELECT ?,?,?,?,1,1,?,'','' WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='initialized')").bind(e.id,JSON.stringify(e),40,['Anmeldung geschlossen','Anmeldung startet bald','Ausgebucht'].includes(e.status)?0:1,e.status==='Warteliste'?1:0)),...Array.from({length:10},(_,index)=>{const n=String(index+1).padStart(2,'0'),now=new Date().toISOString();return db.prepare("INSERT OR IGNORE INTO registrations (id,event_id,first_name,last_name,birth_date,skill,email,phone,note,status,consent_at,created_at) SELECT ?,1,?,?,'2016-01-01',?,?,'0000000000','Fiktiver Testdatensatz – keine echte Anmeldung','confirmed',?,? WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='initialized')").bind('00000000-0000-4000-8000-'+String(index+1).padStart(12,'0'),'Testperson',n,initialEvents[0].skillLevels[index%initialEvents[0].skillLevels.length],'test'+n+'@example.invalid',now,now)}),db.prepare("INSERT OR IGNORE INTO settings (key,value) VALUES ('initialized','1')")]);}
async function eventList(all=false){const rows=await database().prepare(`SELECT e.*, (SELECT COUNT(*) FROM registrations r WHERE r.event_id=e.id AND r.status='confirmed') AS confirmed, (SELECT COUNT(*) FROM registrations r WHERE r.event_id=e.id AND r.status='waitlist') AS waiting FROM events e ${all?'':'WHERE e.visible=1'} ORDER BY e.id`).all<any>();return rows.results.map(row=>{const remaining=Math.max(0,row.capacity-row.confirmed),now=new Date().toISOString();let status='Anmeldung offen';if(!row.active||row.ends&&row.ends<now)status='Anmeldung geschlossen';else if(row.starts&&row.starts>now)status='Anmeldung startet bald';else if(row.only_waitlist||!remaining)status=row.waitlist?'Warteliste':'Ausgebucht';return {...JSON.parse(row.data),id:row.id,capacity:row.capacity,active:!!row.active,visible:!!row.visible,waitlist:!!row.waitlist,onlyWaitlist:!!row.only_waitlist,starts:row.starts,ends:row.ends,confirmed:row.confirmed,waiting:row.waiting,spots:remaining,status};});}
export async function GET(request:Request){try{await seed();const url=new URL(request.url);if(url.searchParams.get('admin')==='1'){if(!await admin(request))return json({error:'Bitte als Administrator anmelden.'},401);const events=await eventList(true);const registrations=await database().prepare('SELECT * FROM registrations ORDER BY created_at,id').all();const settings=await database().prepare("SELECT value FROM settings WHERE key='emails'").first<{value:string}>();return json({events,registrations:registrations.results,emails:settings?JSON.parse(settings.value):{success:'Hallo {{vorname}}, deine Anmeldung für {{veranstaltung}} wurde gespeichert.',wait:'Hallo {{vorname}}, du stehst auf der Warteliste für {{veranstaltung}}.'}});}return json({events:await eventList()});}catch(error){console.error('Database read failed',error);return json({error:'Die Daten konnten nicht geladen werden. Bitte erneut versuchen.'},503);}}
const text=z.string().trim().min(1).max(200);
const registration=z.object({requestId:z.string().uuid(),eventId:z.number().int().positive(),firstName:text,lastName:text,birthDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v<=new Date().toISOString().slice(0,10)&&v>='1900-01-01'),skill:text,email:z.string().trim().email().max(254),phone:z.string().trim().min(3).max(60),note:z.string().max(3000).default(''),consent:z.literal(true)});
const eventSchema=z.object({id:z.number().int().positive().optional(),title:text,detailHeading:text.default("Gemeinsam besser Ski fahren."),date:text,dateLong:text,place:text,description:z.string().max(10000),info:z.array(z.string().max(500)).max(30),registrationInfo:z.string().max(5000),skillLevels:z.array(text).min(1).max(30),imagePosition:z.string().max(50).default('50% 50%'),imageUrl:z.string().max(2000).refine(v=>!v||v.startsWith('/api/images?key=')||v==='/schiteam-momente.jpeg'||/^https:\/\//.test(v)).default(''),showSpots:z.boolean().default(true),capacity:z.number().int().min(1).max(100000),active:z.boolean(),visible:z.boolean(),waitlist:z.boolean(),onlyWaitlist:z.boolean(),starts:z.string().max(40),ends:z.string().max(40)}).refine(v=>(!v.starts||!isNaN(Date.parse(v.starts)))&&(!v.ends||!isNaN(Date.parse(v.ends)))&&(!v.starts||!v.ends||v.starts<v.ends),{message:'Anmeldezeitraum prüfen'});
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)return json({error:'Ungültige Anfrage.'},403);if(request.headers.get('content-type')?.includes('multipart/form-data')){if(!await admin(request))return json({error:'Bitte anmelden.'},401);if(!env.BUCKET)return json({error:'Bildspeicher nicht verfügbar.'},503);if(Number(request.headers.get('content-length')||0)>5500000)return json({error:'Bild maximal 5 MB.'},413);const form=await request.formData();const file=form.get('image');if(!(file instanceof File)||file.size>5000000)return json({error:'Bitte ein Bild bis 5 MB auswählen.'},400);const bytes=new Uint8Array(await file.arrayBuffer());let type='';if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)type='image/png';else if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)type='image/jpeg';else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')type='image/webp';if(!type)return json({error:'Bitte PNG, JPEG oder WebP auswählen.'},400);const key=crypto.randomUUID();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type}});return json({url:'/api/images?key='+key});}if(!request.headers.get('content-type')?.includes('application/json'))return json({error:'JSON erwartet.'},415);const raw=await request.text();if(raw.length>30000)return json({error:'Anfrage zu groß.'},413);const body=JSON.parse(raw);const db=database();
if(body.action==='login'){const key=await hash(request.headers.get('oai-authenticated-user-id')||request.headers.get('cf-connecting-ip')||'shared');const now=Date.now();const attempt=await db.prepare('INSERT INTO login_attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING count').bind(key,now+900000,now,now).first<{count:number}>();if(attempt&&attempt.count>10)return json({error:'Zu viele Anmeldeversuche. Bitte in 15 Minuten erneut versuchen.'},429);if(body.username!=='admin'||typeof body.password!=='string'||await hash(body.password)!==await hash(adminPassword()))return json({error:'Benutzername oder Passwort ist falsch.'},401);const token=crypto.randomUUID()+crypto.randomUUID();await db.batch([db.prepare('DELETE FROM sessions WHERE expires<?').bind(now),db.prepare('INSERT INTO sessions (hash,expires,version) VALUES (?,?,?)').bind(await hash(token),now+28800000,await hash(adminPassword())),db.prepare('DELETE FROM login_attempts WHERE key=?').bind(key)]);const response=json({ok:true});response.headers.set('Set-Cookie',`${cookieName}=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${new URL(request.url).protocol==='https:'?'; Secure':''}`);return response;}
if(body.action==='logout'){const token=request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(token)await db.prepare('DELETE FROM sessions WHERE hash=?').bind(await hash(token)).run();const response=json({ok:true});response.headers.set('Set-Cookie',`${cookieName}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0`);return response;}
if(body.action==='register'){const input=registration.parse(body);const event=(await eventList()).find(e=>e.id===input.eventId);if(!event||!event.skillLevels.includes(input.skill))return json({error:'Veranstaltung oder Könnensstufe ungültig.'},400);const now=new Date().toISOString();const result=await db.prepare(`INSERT INTO registrations (id,event_id,first_name,last_name,birth_date,skill,email,phone,note,status,consent_at,created_at) SELECT ?,id,?,?,?,?,?,?,?,CASE WHEN only_waitlist=1 OR (SELECT COUNT(*) FROM registrations WHERE event_id=events.id AND status='confirmed')>=capacity THEN 'waitlist' ELSE 'confirmed' END,?,? FROM events WHERE id=? AND visible=1 AND active=1 AND (starts='' OR starts<=?) AND (ends='' OR ends>=?) AND ((only_waitlist=0 AND (SELECT COUNT(*) FROM registrations WHERE event_id=events.id AND status='confirmed')<capacity) OR waitlist=1) ON CONFLICT(id) DO NOTHING RETURNING status`).bind(input.requestId,input.firstName,input.lastName,input.birthDate,input.skill,input.email,input.phone,input.note,now,now,input.eventId,now,now).first<{status:string}>();if(result)return json({ok:true,status:result.status});const previous=await db.prepare('SELECT status FROM registrations WHERE id=? AND event_id=? AND email=?').bind(input.requestId,input.eventId,input.email).first<{status:string}>();return previous?json({ok:true,status:previous.status}):json({error:'Die Anmeldung ist geschlossen oder alle Plätze sind vergeben.'},409);}
if(!await admin(request))return json({error:'Bitte als Administrator anmelden.'},401);
if(body.action==='saveEvent'){const event=eventSchema.parse(body.event);const values=[JSON.stringify(event),event.capacity,Number(event.active),Number(event.visible),Number(event.waitlist),Number(event.onlyWaitlist),event.starts,event.ends];if(event.id)await db.prepare('UPDATE events SET data=?,capacity=?,active=?,visible=?,waitlist=?,only_waitlist=?,starts=?,ends=? WHERE id=?').bind(...values,event.id).run();else await db.prepare('INSERT INTO events (data,capacity,active,visible,waitlist,only_waitlist,starts,ends) VALUES (?,?,?,?,?,?,?,?)').bind(...values).run();return json({ok:true});}
if(body.action==='promote'){const id=z.string().uuid().parse(body.id);const row=await db.prepare("UPDATE registrations SET status='confirmed' WHERE id=? AND status='waitlist' AND (SELECT COUNT(*) FROM registrations r WHERE r.event_id=registrations.event_id AND r.status='confirmed')<(SELECT capacity FROM events WHERE id=registrations.event_id) RETURNING id").bind(id).first();return row?json({ok:true}):json({error:'Kein freier Platz vorhanden oder Person bereits übernommen.'},409);}
if(body.action==='saveParticipant'){const input=registration.parse({...body.person,requestId:body.person.id||crypto.randomUUID(),consent:body.person.id?true:body.person.consent});const id=body.person.id?z.string().uuid().parse(body.person.id):input.requestId;const status=z.enum(['confirmed','waitlist']).parse(body.person.status);const event=(await eventList(true)).find(e=>e.id===input.eventId);if(!event||!event.skillLevels.includes(input.skill))return json({error:'Könnensstufe oder Veranstaltung ungültig.'},400);const now=new Date().toISOString();let result;if(body.person.id){result=await db.prepare("UPDATE registrations SET first_name=?,last_name=?,birth_date=?,skill=?,email=?,phone=?,note=?,status=? WHERE id=? AND event_id=? AND (?='waitlist' OR (SELECT COUNT(*) FROM registrations r WHERE r.event_id=registrations.event_id AND r.status='confirmed' AND r.id<>?)<(SELECT capacity FROM events WHERE id=registrations.event_id)) RETURNING id").bind(input.firstName,input.lastName,input.birthDate,input.skill,input.email,input.phone,input.note,status,id,input.eventId,status,id).first();}else{result=await db.prepare("INSERT INTO registrations (id,event_id,first_name,last_name,birth_date,skill,email,phone,note,status,consent_at,created_at) SELECT ?,id,?,?,?,?,?,?,?,?,?,? FROM events WHERE id=? AND (?='waitlist' OR (SELECT COUNT(*) FROM registrations WHERE event_id=events.id AND status='confirmed')<capacity) RETURNING id").bind(id,input.firstName,input.lastName,input.birthDate,input.skill,input.email,input.phone,input.note,status,now,now,input.eventId,status).first();}return result?json({ok:true}):json({error:'Kein freier Platz vorhanden oder Anmeldung nicht gefunden.'},409);}
if(body.action==='deleteParticipant'){await db.prepare('DELETE FROM registrations WHERE id=?').bind(z.string().uuid().parse(body.id)).run();return json({ok:true});}
if(body.action==='saveEmails'){const emails=z.object({success:z.string().max(10000),wait:z.string().max(10000),successSubject:z.string().max(300).optional(),waitSubject:z.string().max(300).optional()}).parse(body.emails);await db.prepare("INSERT INTO settings (key,value) VALUES ('emails',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(emails)).run();return json({ok:true});}
return json({error:'Unbekannte Aktion.'},400);
}catch(error){if(error instanceof z.ZodError||error instanceof SyntaxError)return json({error:'Bitte alle Eingaben und den Anmeldezeitraum prüfen.'},400);console.error('Database write failed',error);return json({error:'Speichern fehlgeschlagen. Deine Eingaben bleiben erhalten. Bitte erneut versuchen.'},503);}}
